name: test
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    # command: npm run dev
    
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    
  otel:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./otel/config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 8889:8889
      - 4318:4318

  sequencer:
    build:
      context: .
      dockerfile: sequencer/Dockerfile
    # Share IPC space so other containers can access the /dev/shm message queues
    ipc: shareable
    command: sleep infinity


